version: '3.4'

services:
  psql-db:
    container_name: psql-db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws-network

volumes:
  postgres_data:

networks:
  ws-network: